//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.1。
// 
namespace TaoBaoDataServer.WinClientData.BusinessLayer.WService
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "WebServiceForTBKeywordsSoap", Namespace = "http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TKCTopApi))]
    public partial class ServiceSplitWord : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback ShowCutByTitleOperationCompleted;

        private System.Threading.SendOrPostCallback ShowMeTheKeywordsByItemIdOperationCompleted;

        private System.Threading.SendOrPostCallback ShowMeTheKeywordsByKeywordOperationCompleted;

        private System.Threading.SendOrPostCallback SplitWordPanGuOperationCompleted;

        private System.Threading.SendOrPostCallback SplitWordPanGuForCreativeOperationCompleted;

        /// <remarks/>
        public ServiceSplitWord()
        {
            this.Url = "http://ci.taokuaiche.com/WebServiceForTBKeywords.asmx";
        }

        /// <remarks/>
        public event ShowCutByTitleCompletedEventHandler ShowCutByTitleCompleted;

        /// <remarks/>
        public event ShowMeTheKeywordsByItemIdCompletedEventHandler ShowMeTheKeywordsByItemIdCompleted;

        /// <remarks/>
        public event ShowMeTheKeywordsByKeywordCompletedEventHandler ShowMeTheKeywordsByKeywordCompleted;

        /// <remarks/>
        public event SplitWordPanGuCompletedEventHandler SplitWordPanGuCompleted;

        /// <remarks/>
        public event SplitWordPanGuForCreativeCompletedEventHandler SplitWordPanGuForCreativeCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ShowCutByTitle", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public JsonResponseTKC ShowCutByTitle(string title, int type, string nick, string topsession)
        {
            object[] results = this.Invoke("ShowCutByTitle", new object[] {
                        title,
                        type,
                        nick,
                        topsession});
            return ((JsonResponseTKC)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginShowCutByTitle(string title, int type, string nick, string topsession, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ShowCutByTitle", new object[] {
                        title,
                        type,
                        nick,
                        topsession}, callback, asyncState);
        }

        /// <remarks/>
        public JsonResponseTKC EndShowCutByTitle(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((JsonResponseTKC)(results[0]));
        }

        /// <remarks/>
        public void ShowCutByTitleAsync(string title, int type, string nick, string topsession)
        {
            this.ShowCutByTitleAsync(title, type, nick, topsession, null);
        }

        /// <remarks/>
        public void ShowCutByTitleAsync(string title, int type, string nick, string topsession, object userState)
        {
            if ((this.ShowCutByTitleOperationCompleted == null))
            {
                this.ShowCutByTitleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowCutByTitleOperationCompleted);
            }
            this.InvokeAsync("ShowCutByTitle", new object[] {
                        title,
                        type,
                        nick,
                        topsession}, this.ShowCutByTitleOperationCompleted, userState);
        }

        private void OnShowCutByTitleOperationCompleted(object arg)
        {
            if ((this.ShowCutByTitleCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShowCutByTitleCompleted(this, new ShowCutByTitleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ShowMeTheKeywordsByItemId", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public JsonResponseTKC ShowMeTheKeywordsByItemId(long ItemId, int type, string nick, string topsession)
        {
            object[] results = this.Invoke("ShowMeTheKeywordsByItemId", new object[] {
                        ItemId,
                        type,
                        nick,
                        topsession});
            return ((JsonResponseTKC)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginShowMeTheKeywordsByItemId(long ItemId, int type, string nick, string topsession, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ShowMeTheKeywordsByItemId", new object[] {
                        ItemId,
                        type,
                        nick,
                        topsession}, callback, asyncState);
        }

        /// <remarks/>
        public JsonResponseTKC EndShowMeTheKeywordsByItemId(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((JsonResponseTKC)(results[0]));
        }

        /// <remarks/>
        public void ShowMeTheKeywordsByItemIdAsync(long ItemId, int type, string nick, string topsession)
        {
            this.ShowMeTheKeywordsByItemIdAsync(ItemId, type, nick, topsession, null);
        }

        /// <remarks/>
        public void ShowMeTheKeywordsByItemIdAsync(long ItemId, int type, string nick, string topsession, object userState)
        {
            if ((this.ShowMeTheKeywordsByItemIdOperationCompleted == null))
            {
                this.ShowMeTheKeywordsByItemIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowMeTheKeywordsByItemIdOperationCompleted);
            }
            this.InvokeAsync("ShowMeTheKeywordsByItemId", new object[] {
                        ItemId,
                        type,
                        nick,
                        topsession}, this.ShowMeTheKeywordsByItemIdOperationCompleted, userState);
        }

        private void OnShowMeTheKeywordsByItemIdOperationCompleted(object arg)
        {
            if ((this.ShowMeTheKeywordsByItemIdCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShowMeTheKeywordsByItemIdCompleted(this, new ShowMeTheKeywordsByItemIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ShowMeTheKeywordsByKeyword", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public JsonResponseTKC ShowMeTheKeywordsByKeyword(string keyword, int type, string nick, string topsession)
        {
            object[] results = this.Invoke("ShowMeTheKeywordsByKeyword", new object[] {
                        keyword,
                        type,
                        nick,
                        topsession});
            return ((JsonResponseTKC)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginShowMeTheKeywordsByKeyword(string keyword, int type, string nick, string topsession, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ShowMeTheKeywordsByKeyword", new object[] {
                        keyword,
                        type,
                        nick,
                        topsession}, callback, asyncState);
        }

        /// <remarks/>
        public JsonResponseTKC EndShowMeTheKeywordsByKeyword(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((JsonResponseTKC)(results[0]));
        }

        /// <remarks/>
        public void ShowMeTheKeywordsByKeywordAsync(string keyword, int type, string nick, string topsession)
        {
            this.ShowMeTheKeywordsByKeywordAsync(keyword, type, nick, topsession, null);
        }

        /// <remarks/>
        public void ShowMeTheKeywordsByKeywordAsync(string keyword, int type, string nick, string topsession, object userState)
        {
            if ((this.ShowMeTheKeywordsByKeywordOperationCompleted == null))
            {
                this.ShowMeTheKeywordsByKeywordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowMeTheKeywordsByKeywordOperationCompleted);
            }
            this.InvokeAsync("ShowMeTheKeywordsByKeyword", new object[] {
                        keyword,
                        type,
                        nick,
                        topsession}, this.ShowMeTheKeywordsByKeywordOperationCompleted, userState);
        }

        private void OnShowMeTheKeywordsByKeywordOperationCompleted(object arg)
        {
            if ((this.ShowMeTheKeywordsByKeywordCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShowMeTheKeywordsByKeywordCompleted(this, new ShowMeTheKeywordsByKeywordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SplitWordPanGu", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SplitWordPanGu(string keyword)
        {
            object[] results = this.Invoke("SplitWordPanGu", new object[] {
                        keyword});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSplitWordPanGu(string keyword, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SplitWordPanGu", new object[] {
                        keyword}, callback, asyncState);
        }

        /// <remarks/>
        public string EndSplitWordPanGu(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void SplitWordPanGuAsync(string keyword)
        {
            this.SplitWordPanGuAsync(keyword, null);
        }

        /// <remarks/>
        public void SplitWordPanGuAsync(string keyword, object userState)
        {
            if ((this.SplitWordPanGuOperationCompleted == null))
            {
                this.SplitWordPanGuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSplitWordPanGuOperationCompleted);
            }
            this.InvokeAsync("SplitWordPanGu", new object[] {
                        keyword}, this.SplitWordPanGuOperationCompleted, userState);
        }

        private void OnSplitWordPanGuOperationCompleted(object arg)
        {
            if ((this.SplitWordPanGuCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SplitWordPanGuCompleted(this, new SplitWordPanGuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SplitWordPanGuForCreative", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SplitWordPanGuForCreative(string keyword)
        {
            object[] results = this.Invoke("SplitWordPanGuForCreative", new object[] {
                        keyword});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSplitWordPanGuForCreative(string keyword, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SplitWordPanGuForCreative", new object[] {
                        keyword}, callback, asyncState);
        }

        /// <remarks/>
        public string EndSplitWordPanGuForCreative(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void SplitWordPanGuForCreativeAsync(string keyword)
        {
            this.SplitWordPanGuForCreativeAsync(keyword, null);
        }

        /// <remarks/>
        public void SplitWordPanGuForCreativeAsync(string keyword, object userState)
        {
            if ((this.SplitWordPanGuForCreativeOperationCompleted == null))
            {
                this.SplitWordPanGuForCreativeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSplitWordPanGuForCreativeOperationCompleted);
            }
            this.InvokeAsync("SplitWordPanGuForCreative", new object[] {
                        keyword}, this.SplitWordPanGuForCreativeOperationCompleted, userState);
        }

        private void OnSplitWordPanGuForCreativeOperationCompleted(object arg)
        {
            if ((this.SplitWordPanGuForCreativeCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SplitWordPanGuForCreativeCompleted(this, new SplitWordPanGuForCreativeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class JsonResponseTKC : TKCTopApi
    {

        private string josnStrField;

        private string pcnameField;

        private string cidnoField;

        private string pcidnoField;

        private string cnameField;

        private string mainstrField;

        private string mycutField;

        private string leftField;

        /// <remarks/>
        public string josnStr
        {
            get
            {
                return this.josnStrField;
            }
            set
            {
                this.josnStrField = value;
            }
        }

        /// <remarks/>
        public string pcname
        {
            get
            {
                return this.pcnameField;
            }
            set
            {
                this.pcnameField = value;
            }
        }

        /// <remarks/>
        public string cidno
        {
            get
            {
                return this.cidnoField;
            }
            set
            {
                this.cidnoField = value;
            }
        }

        /// <remarks/>
        public string pcidno
        {
            get
            {
                return this.pcidnoField;
            }
            set
            {
                this.pcidnoField = value;
            }
        }

        /// <remarks/>
        public string cname
        {
            get
            {
                return this.cnameField;
            }
            set
            {
                this.cnameField = value;
            }
        }

        /// <remarks/>
        public string mainstr
        {
            get
            {
                return this.mainstrField;
            }
            set
            {
                this.mainstrField = value;
            }
        }

        /// <remarks/>
        public string mycut
        {
            get
            {
                return this.mycutField;
            }
            set
            {
                this.mycutField = value;
            }
        }

        /// <remarks/>
        public string left
        {
            get
            {
                return this.leftField;
            }
            set
            {
                this.leftField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JsonResponseTKC))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class TKCTopApi
    {

        private bool isAPIErrorField;

        private bool isLocalErrorField;

        private string subErrorMsgField;

        private string otherErrorMsgField;

        /// <remarks/>
        public bool isAPIError
        {
            get
            {
                return this.isAPIErrorField;
            }
            set
            {
                this.isAPIErrorField = value;
            }
        }

        /// <remarks/>
        public bool isLocalError
        {
            get
            {
                return this.isLocalErrorField;
            }
            set
            {
                this.isLocalErrorField = value;
            }
        }

        /// <remarks/>
        public string subErrorMsg
        {
            get
            {
                return this.subErrorMsgField;
            }
            set
            {
                this.subErrorMsgField = value;
            }
        }

        /// <remarks/>
        public string otherErrorMsg
        {
            get
            {
                return this.otherErrorMsgField;
            }
            set
            {
                this.otherErrorMsgField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void ShowCutByTitleCompletedEventHandler(object sender, ShowCutByTitleCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShowCutByTitleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ShowCutByTitleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public JsonResponseTKC Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((JsonResponseTKC)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void ShowMeTheKeywordsByItemIdCompletedEventHandler(object sender, ShowMeTheKeywordsByItemIdCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShowMeTheKeywordsByItemIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ShowMeTheKeywordsByItemIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public JsonResponseTKC Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((JsonResponseTKC)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void ShowMeTheKeywordsByKeywordCompletedEventHandler(object sender, ShowMeTheKeywordsByKeywordCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShowMeTheKeywordsByKeywordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ShowMeTheKeywordsByKeywordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public JsonResponseTKC Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((JsonResponseTKC)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void SplitWordPanGuCompletedEventHandler(object sender, SplitWordPanGuCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SplitWordPanGuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SplitWordPanGuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void SplitWordPanGuForCreativeCompletedEventHandler(object sender, SplitWordPanGuForCreativeCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SplitWordPanGuForCreativeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SplitWordPanGuForCreativeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}