//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeywordCategoryForecast", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EntityKeywordCategoryForecast : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categroy_wordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.EntityCategoryInfo[] category_childField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string categroy_word {
            get {
                return this.categroy_wordField;
            }
            set {
                if ((object.ReferenceEquals(this.categroy_wordField, value) != true)) {
                    this.categroy_wordField = value;
                    this.RaisePropertyChanged("categroy_word");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.EntityCategoryInfo[] category_child {
            get {
                return this.category_childField;
            }
            set {
                if ((object.ReferenceEquals(this.category_childField, value) != true)) {
                    this.category_childField = value;
                    this.RaisePropertyChanged("category_child");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityCategoryInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EntityCategoryInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string category_descField;
        
        private long category_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string category_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string category_desc {
            get {
                return this.category_descField;
            }
            set {
                if ((object.ReferenceEquals(this.category_descField, value) != true)) {
                    this.category_descField = value;
                    this.RaisePropertyChanged("category_desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long category_id {
            get {
                return this.category_idField;
            }
            set {
                if ((this.category_idField.Equals(value) != true)) {
                    this.category_idField = value;
                    this.RaisePropertyChanged("category_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string category_name {
            get {
                return this.category_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.category_nameField, value) != true)) {
                    this.category_nameField = value;
                    this.RaisePropertyChanged("category_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityWordBase", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EntityWordBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string wordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.EntityBaseInfo[] reord_baseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string word {
            get {
                return this.wordField;
            }
            set {
                if ((object.ReferenceEquals(this.wordField, value) != true)) {
                    this.wordField = value;
                    this.RaisePropertyChanged("word");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.EntityBaseInfo[] reord_base {
            get {
                return this.reord_baseField;
            }
            set {
                if ((object.ReferenceEquals(this.reord_baseField, value) != true)) {
                    this.reord_baseField = value;
                    this.RaisePropertyChanged("reord_base");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBaseInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EntityBaseInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long impressionField;
        
        private long clickField;
        
        private long competitionField;
        
        private long avg_priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ctrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long impression {
            get {
                return this.impressionField;
            }
            set {
                if ((this.impressionField.Equals(value) != true)) {
                    this.impressionField = value;
                    this.RaisePropertyChanged("impression");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long click {
            get {
                return this.clickField;
            }
            set {
                if ((this.clickField.Equals(value) != true)) {
                    this.clickField = value;
                    this.RaisePropertyChanged("click");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long competition {
            get {
                return this.competitionField;
            }
            set {
                if ((this.competitionField.Equals(value) != true)) {
                    this.competitionField = value;
                    this.RaisePropertyChanged("competition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long avg_price {
            get {
                return this.avg_priceField;
            }
            set {
                if ((this.avg_priceField.Equals(value) != true)) {
                    this.avg_priceField = value;
                    this.RaisePropertyChanged("avg_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ctr {
            get {
                return this.ctrField;
            }
            set {
                if ((object.ReferenceEquals(this.ctrField, value) != true)) {
                    this.ctrField = value;
                    this.RaisePropertyChanged("ctr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                if ((object.ReferenceEquals(this.dateField, value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaoBaoDataServer.WService.WebServiceForKeywordForecastSoap")]
    public interface WebServiceForKeywordForecastSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.HelloWorldResponse HelloWorld(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strKeywords 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KeywordForecastCache", ReplyAction="*")]
        TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordForecastCacheResponse KeywordForecastCache(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordForecastCacheRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strKeywords 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KeywordBaseCache", ReplyAction="*")]
        TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordBaseCacheResponse KeywordBaseCache(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordBaseCacheRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 key 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetValue", ReplyAction="*")]
        TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetValueResponse GetValue(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetValueRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 key 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetValue", ReplyAction="*")]
        TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.SetValueResponse SetValue(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.SetValueRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 key 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveKey", ReplyAction="*")]
        TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.RemoveKeyResponse RemoveKey(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.RemoveKeyRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 key 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllKeys", ReplyAction="*")]
        TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetAllKeysResponse GetAllKeys(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetAllKeysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FlushDB", ReplyAction="*")]
        void FlushDB();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KeywordForecastCacheRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KeywordForecastCache", Namespace="http://tempuri.org/", Order=0)]
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordForecastCacheRequestBody Body;
        
        public KeywordForecastCacheRequest() {
        }
        
        public KeywordForecastCacheRequest(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordForecastCacheRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KeywordForecastCacheRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strKeywords;
        
        public KeywordForecastCacheRequestBody() {
        }
        
        public KeywordForecastCacheRequestBody(string strKeywords) {
            this.strKeywords = strKeywords;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KeywordForecastCacheResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KeywordForecastCacheResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordForecastCacheResponseBody Body;
        
        public KeywordForecastCacheResponse() {
        }
        
        public KeywordForecastCacheResponse(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordForecastCacheResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KeywordForecastCacheResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.EntityKeywordCategoryForecast[] KeywordForecastCacheResult;
        
        public KeywordForecastCacheResponseBody() {
        }
        
        public KeywordForecastCacheResponseBody(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.EntityKeywordCategoryForecast[] KeywordForecastCacheResult) {
            this.KeywordForecastCacheResult = KeywordForecastCacheResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KeywordBaseCacheRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KeywordBaseCache", Namespace="http://tempuri.org/", Order=0)]
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordBaseCacheRequestBody Body;
        
        public KeywordBaseCacheRequest() {
        }
        
        public KeywordBaseCacheRequest(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordBaseCacheRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KeywordBaseCacheRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strKeywords;
        
        public KeywordBaseCacheRequestBody() {
        }
        
        public KeywordBaseCacheRequestBody(string strKeywords) {
            this.strKeywords = strKeywords;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KeywordBaseCacheResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KeywordBaseCacheResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordBaseCacheResponseBody Body;
        
        public KeywordBaseCacheResponse() {
        }
        
        public KeywordBaseCacheResponse(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordBaseCacheResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KeywordBaseCacheResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.EntityWordBase[] KeywordBaseCacheResult;
        
        public KeywordBaseCacheResponseBody() {
        }
        
        public KeywordBaseCacheResponseBody(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.EntityWordBase[] KeywordBaseCacheResult) {
            this.KeywordBaseCacheResult = KeywordBaseCacheResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValue", Namespace="http://tempuri.org/", Order=0)]
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetValueRequestBody Body;
        
        public GetValueRequest() {
        }
        
        public GetValueRequest(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        public GetValueRequestBody() {
        }
        
        public GetValueRequestBody(string key) {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValueResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetValueResponseBody Body;
        
        public GetValueResponse() {
        }
        
        public GetValueResponse(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetValueResult;
        
        public GetValueResponseBody() {
        }
        
        public GetValueResponseBody(string GetValueResult) {
            this.GetValueResult = GetValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetValue", Namespace="http://tempuri.org/", Order=0)]
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.SetValueRequestBody Body;
        
        public SetValueRequest() {
        }
        
        public SetValueRequest(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.SetValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string value;
        
        public SetValueRequestBody() {
        }
        
        public SetValueRequestBody(string key, string value) {
            this.key = key;
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetValueResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.SetValueResponseBody Body;
        
        public SetValueResponse() {
        }
        
        public SetValueResponse(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.SetValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetValueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetValueResult;
        
        public SetValueResponseBody() {
        }
        
        public SetValueResponseBody(bool SetValueResult) {
            this.SetValueResult = SetValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveKey", Namespace="http://tempuri.org/", Order=0)]
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.RemoveKeyRequestBody Body;
        
        public RemoveKeyRequest() {
        }
        
        public RemoveKeyRequest(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.RemoveKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        public RemoveKeyRequestBody() {
        }
        
        public RemoveKeyRequestBody(string key) {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.RemoveKeyResponseBody Body;
        
        public RemoveKeyResponse() {
        }
        
        public RemoveKeyResponse(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.RemoveKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RemoveKeyResult;
        
        public RemoveKeyResponseBody() {
        }
        
        public RemoveKeyResponseBody(bool RemoveKeyResult) {
            this.RemoveKeyResult = RemoveKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllKeysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllKeys", Namespace="http://tempuri.org/", Order=0)]
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetAllKeysRequestBody Body;
        
        public GetAllKeysRequest() {
        }
        
        public GetAllKeysRequest(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetAllKeysRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllKeysRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        public GetAllKeysRequestBody() {
        }
        
        public GetAllKeysRequestBody(string key) {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllKeysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllKeysResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetAllKeysResponseBody Body;
        
        public GetAllKeysResponse() {
        }
        
        public GetAllKeysResponse(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetAllKeysResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllKeysResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.ArrayOfString GetAllKeysResult;
        
        public GetAllKeysResponseBody() {
        }
        
        public GetAllKeysResponseBody(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.ArrayOfString GetAllKeysResult) {
            this.GetAllKeysResult = GetAllKeysResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceForKeywordForecastSoapChannel : TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.WebServiceForKeywordForecastSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceForKeywordForecastSoapClient : System.ServiceModel.ClientBase<TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.WebServiceForKeywordForecastSoap>, TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.WebServiceForKeywordForecastSoap {
        
        public WebServiceForKeywordForecastSoapClient() {
        }
        
        public WebServiceForKeywordForecastSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceForKeywordForecastSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceForKeywordForecastSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceForKeywordForecastSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.HelloWorldResponse TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.WebServiceForKeywordForecastSoap.HelloWorld(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.HelloWorldRequest inValue = new TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.HelloWorldRequest();
            inValue.Body = new TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.HelloWorldRequestBody();
            TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.HelloWorldResponse retVal = ((TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.WebServiceForKeywordForecastSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordForecastCacheResponse TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.WebServiceForKeywordForecastSoap.KeywordForecastCache(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordForecastCacheRequest request) {
            return base.Channel.KeywordForecastCache(request);
        }
        
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.EntityKeywordCategoryForecast[] KeywordForecastCache(string strKeywords) {
            TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordForecastCacheRequest inValue = new TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordForecastCacheRequest();
            inValue.Body = new TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordForecastCacheRequestBody();
            inValue.Body.strKeywords = strKeywords;
            TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordForecastCacheResponse retVal = ((TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.WebServiceForKeywordForecastSoap)(this)).KeywordForecastCache(inValue);
            return retVal.Body.KeywordForecastCacheResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordBaseCacheResponse TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.WebServiceForKeywordForecastSoap.KeywordBaseCache(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordBaseCacheRequest request) {
            return base.Channel.KeywordBaseCache(request);
        }
        
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.EntityWordBase[] KeywordBaseCache(string strKeywords) {
            TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordBaseCacheRequest inValue = new TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordBaseCacheRequest();
            inValue.Body = new TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordBaseCacheRequestBody();
            inValue.Body.strKeywords = strKeywords;
            TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.KeywordBaseCacheResponse retVal = ((TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.WebServiceForKeywordForecastSoap)(this)).KeywordBaseCache(inValue);
            return retVal.Body.KeywordBaseCacheResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetValueResponse TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.WebServiceForKeywordForecastSoap.GetValue(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetValueRequest request) {
            return base.Channel.GetValue(request);
        }
        
        public string GetValue(string key) {
            TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetValueRequest inValue = new TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetValueRequest();
            inValue.Body = new TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetValueRequestBody();
            inValue.Body.key = key;
            TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetValueResponse retVal = ((TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.WebServiceForKeywordForecastSoap)(this)).GetValue(inValue);
            return retVal.Body.GetValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.SetValueResponse TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.WebServiceForKeywordForecastSoap.SetValue(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.SetValueRequest request) {
            return base.Channel.SetValue(request);
        }
        
        public bool SetValue(string key, string value) {
            TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.SetValueRequest inValue = new TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.SetValueRequest();
            inValue.Body = new TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.SetValueRequestBody();
            inValue.Body.key = key;
            inValue.Body.value = value;
            TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.SetValueResponse retVal = ((TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.WebServiceForKeywordForecastSoap)(this)).SetValue(inValue);
            return retVal.Body.SetValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.RemoveKeyResponse TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.WebServiceForKeywordForecastSoap.RemoveKey(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.RemoveKeyRequest request) {
            return base.Channel.RemoveKey(request);
        }
        
        public bool RemoveKey(string key) {
            TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.RemoveKeyRequest inValue = new TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.RemoveKeyRequest();
            inValue.Body = new TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.RemoveKeyRequestBody();
            inValue.Body.key = key;
            TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.RemoveKeyResponse retVal = ((TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.WebServiceForKeywordForecastSoap)(this)).RemoveKey(inValue);
            return retVal.Body.RemoveKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetAllKeysResponse TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.WebServiceForKeywordForecastSoap.GetAllKeys(TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetAllKeysRequest request) {
            return base.Channel.GetAllKeys(request);
        }
        
        public TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.ArrayOfString GetAllKeys(string key) {
            TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetAllKeysRequest inValue = new TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetAllKeysRequest();
            inValue.Body = new TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetAllKeysRequestBody();
            inValue.Body.key = key;
            TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.GetAllKeysResponse retVal = ((TaoBaoDataServer.WinClientData.TaoBaoDataServer.WService.WebServiceForKeywordForecastSoap)(this)).GetAllKeys(inValue);
            return retVal.Body.GetAllKeysResult;
        }
        
        public void FlushDB() {
            base.Channel.FlushDB();
        }
    }
}
